application: instafetcher
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /public
  static_dir: static

- url: /cron/fetch
  script: main.app

- url: /_ah/spi/.*
  script: instafetcher_api.APPLICATION

libraries:
- name: webapp2
  version: "2.5.2"
- name: endpoints
  version: 1.0
- name: pycrypto
  version: latest