application: instafetcher
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

# Just for debugging purpose.
# Front-end is hosted at http://giacomocusinato.com/instafetcher
- url: /public
  static_dir: view

# Cron handler
- url: /cron/fetch
  script: task.cron.app

# Endpoints handler
- url: /_ah/spi/.*
  script: api.instafetcher_api.APPLICATION

libraries:
- name: webapp2
  version: "2.5.2"
- name: endpoints
  version: 1.0
- name: pycrypto
  version: latest